/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import javax.swing.JProgressBar;


/**
 *
 * @author Rafael
 */
public class TelaPrincipal extends javax.swing.JFrame {

    File arquivo = null;
    File backup = null;
    InputStream is = null;
    OutputStream os = null;
    Core c = null;
    
    public TelaPrincipal() {
        this.setTitle("RFBackuper");
        this.setLocationRelativeTo(null);
        initComponents();
        this.c = new Core(TelaPrincipal.this);
    }
       
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        botaoSelecionarArquivo = new javax.swing.JButton();
        botaoSelecionarDestino = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        botaoFechar = new javax.swing.JButton();
        botaoBackup = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        getContentPane().setLayout(layout);

        botaoSelecionarArquivo.setText("Selecionar");
        botaoSelecionarArquivo.setToolTipText("");
        botaoSelecionarArquivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoSelecionarArquivoMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        getContentPane().add(botaoSelecionarArquivo, gridBagConstraints);
        botaoSelecionarArquivo.getAccessibleContext().setAccessibleName("jButton1");

        botaoSelecionarDestino.setText("Selecionar");
        botaoSelecionarDestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoSelecionarDestinoMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        getContentPane().add(botaoSelecionarDestino, gridBagConstraints);

        jLabel1.setText("Caminho do arquivo de origem:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jTextField1.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 205;
        getContentPane().add(jTextField1, gridBagConstraints);

        jLabel2.setText("Caminho do arquivo de destino:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jTextField2.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 205;
        getContentPane().add(jTextField2, gridBagConstraints);

        botaoFechar.setText("Fechar");
        botaoFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoFecharMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 76, 5, 5);
        getContentPane().add(botaoFechar, gridBagConstraints);

        botaoBackup.setText("Backup!");
        botaoBackup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoBackupMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 72);
        getContentPane().add(botaoBackup, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FileInputStream", "BufferedInputStream" }));
        jComboBox1.setSelectedIndex(1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 32;
        getContentPane().add(jComboBox1, gridBagConstraints);

        jLabel3.setText("Modo de operação:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        getContentPane().add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jProgressBar1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSelecionarArquivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSelecionarArquivoMouseClicked
        FileChooserFactory file = new FileChooserFactory(); 
        int i= file.showOpenDialog(null);
        
        if (i!=1){
            arquivo = file.getSelectedFile();
            this.jTextField1.setText(arquivo.getPath());
            System.out.println(arquivo.getPath());
        }
    }//GEN-LAST:event_botaoSelecionarArquivoMouseClicked

    private void botaoSelecionarDestinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSelecionarDestinoMouseClicked
        FileChooserFactory file = new FileChooserFactory(); 
        int i= file.showSaveDialog(null);
        
        if (i!=1){
            backup = file.getSelectedFile();
            this.jTextField2.setText(backup.getPath());
            System.out.println(backup.getPath());
        }
    }//GEN-LAST:event_botaoSelecionarDestinoMouseClicked

    private void botaoBackupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoBackupMouseClicked
        int op = this.jComboBox1.getSelectedIndex();

        try {
            is = new FileInputStream(arquivo.getPath());
            os = new FileOutputStream(backup.getPath());
        } catch (FileNotFoundException ex) {
            System.out.println("Algo errado aconteceu");
        }

        if(op == 1){
            is = new BufferedInputStream(is);
            os = new BufferedOutputStream(os);
        }

        this.jProgressBar1.setMaximum((int)arquivo.length());
        
        //Core c = new Core();
        try {
            c.fazerBackup(is, os);
        } catch (Exception ex) {
            System.out.println("Deu ruim no backup" + ex);
        }
    }//GEN-LAST:event_botaoBackupMouseClicked

    private void botaoFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharMouseClicked
        this.dispose();
    }//GEN-LAST:event_botaoFecharMouseClicked
    
    public void atualizarProgressbar(int valor){
        this.jProgressBar1.setValue(valor);
    }
    
    public JProgressBar getProgressBar(){
        return this.jProgressBar1;
    }
      
    
    
    public static void main(String args[]) {
                
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBackup;
    private javax.swing.JButton botaoFechar;
    private javax.swing.JButton botaoSelecionarArquivo;
    private javax.swing.JButton botaoSelecionarDestino;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
